# Generated by Django 3.2.13 on 2023-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=50)),
                ('subject_type', models.IntegerField(choices=[(1, 'Архитектура предприятия'), (2, 'Интеллектуальный анализ данных'), (3, 'Информационная безопасность IT инфраструктуры'), (4, 'Гибкие технологии Agile'), (5, 'Информационные системы и информационно-коммуникационные технологии управления бизнесом'), (6, 'Проектирование бизнес-процессов'), (7, 'Проектная деятельность')])),
                ('state', models.IntegerField(choices=[(1, 'stable'), (2, 'writing')])),
            ],
        ),
    ]
